export const  Constantes = {
  CONST_COD_PERFIL_ADM: "3", 
  CONST_NOMBRE_PERFIL_ADM: "ADMINISTRADOR", 
  CONST_COD_PERFIL_VENDENDOR: "2",
  CONST_NOMBRE_PERFIL_VENDENDOR: "VENDEDOR",
  CONST_COD_PERFIL_CLIENTE: "1",
  CONST_NOMBRE_PERFIL_CLIENTE: "CLIENTE",
  CONST_PARAM_IN_PATH: "nuevo"
}